development: &default
  adapter: postgresql
  host: localhost
  username: postgres
  database: create-rails-app-server_dev
  pool: 5
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  username: postgres
  database: create-rails-app-server_test

staging:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
